### ISSUE TITLE
Error after updating from v0.6.2 to v0.7 beta 1

### ISSUE THREAD

**Issue by anaggh** [dignajar/bludit#133]
Copied the content dir as usual from the older release to the newer release and set the right permissions.
Error on all pages.
```
Fatal error: Call to a member function format() on a non-object in /var/www/html/blog/kernel/helpers/date.class.php on line 30
```

**Comment by hxii** [comment]
Same issue. Full error via HHVM.
```
[Mon Nov 30 06:31:01 2015] [hphp] [1607:7fe2d9bff700:1159:000001] [] \nFatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function format() on a non-object (boolean)' in /var/www/somn.us/htdocs/kernel/helpers/date.class.php:30\nStack trace:\n#0 /var/www/somn.us/htdocs/kernel/page.class.php(93): Date::format()\n#1 /var/www/somn.us/htdocs/kernel/boot/rules/70.pages.php(66): Page->dateRaw()\n#2 /var/www/somn.us/htdocs/kernel/boot/rules/70.pages.php(93): build_page()\n#3 /var/www/somn.us/htdocs/kernel/boot/rules/70.pages.php(188): build_all_pages()\n#4 /var/www/somn.us/htdocs/kernel/boot/site.php(5): include()\n#5 /var/www/somn.us/htdocs/index.php(40): include()\n#6 {main}
```

**Comment by dignajar** [comment]
Fixed! could you update the file /var/www/html/blog/kernel/helpers/date.class.php

**Comment by anaggh** [comment]
Thanks. Replaced with https://raw.githubusercontent.com/dignajar/bludit/master/kernel/helpers/date.class.php and its fixed. Btw, is it better to use the master branch instead of 0.7 beta1?

**Comment by dignajar** [comment]
Both are beta, but the master branch has the lastest changes and bug fixes, and maybe new bugs :D
